name: najot_talim_nt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  open_filex: ^4.4.0
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/bodoni/
    - assets/fonts/inter/
    - assets/lottie/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Bodoni
      fonts:
        - asset: assets/fonts/bodoni/BodoniFLF-Bold.ttf
        - asset: assets/fonts/bodoni/BodoniFLF-BoldItalic.ttf
        - asset: assets/fonts/bodoni/BodoniFLF-Italic.ttf
          style: italic
        - asset: assets/fonts/bodoni/BodoniFLF-Roman.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Italic.otf
        - asset: assets/fonts/inter/Inter-Light.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-SemiBold.otf