// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5WKzcB8bkbvs5BG4saBmxcPO_t5AIeNc',
    appId: '1:247041905668:android:c63f784dacfd24ac32d151',
    messagingSenderId: '247041905668',
    projectId: 'nur-pay-680cd',
    storageBucket: 'nur-pay-680cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz6ez5dkSMCG31BGFCCqGZR7wGL7HT9RE',
    appId: '1:247041905668:ios:5b701ff8062024b732d151',
    messagingSenderId: '247041905668',
    projectId: 'nur-pay-680cd',
    storageBucket: 'nur-pay-680cd.appspot.com',
    androidClientId: '247041905668-lqqkepvn9k6d2ssqbbqrppjbl48g5at5.apps.googleusercontent.com',
    iosClientId: '247041905668-im16va82dqvvkcgdbtbkoqsvn63e81nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.najotTalimNt',
  );
}
